#!/usr/bin/env python3
"""Generic HC49S rendering model; millimetres, converted to KiCad VRML units.

Envelope/pitch: Elecsound HC49S DIP drawing. Seam/base details approximate.
Not a manufacturer identification or measured model of the stocked crystals.
"""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'kicad/rig/DCJRig.3dshapes/Crystal_HC49S_Vertical.wrl'


def stadium(length, width):
    r = width / 2
    d = (length - width) / 2
    return [(2.44 + c + r * math.cos(math.radians(a)),
             r * math.sin(math.radians(a)))
            for c, start in [(d, -90), (-d, 90)]
            for a in range(start, start + 181, 10)]


def prism(outline, bottom, top, color):
    n = len(outline)
    vertices = [(x, y, z) for z in (bottom, top) for x, y in outline]
    faces = [list(reversed(range(n))), list(range(n, n * 2))]
    faces += [[i, (i + 1) % n, (i + 1) % n + n, i + n] for i in range(n)]
    lines = ['Shape { appearance Appearance { material Material {',
             'diffuseColor ' + ' '.join(map(str, color)),
             'specularColor 0.6 0.6 0.6 shininess 0.7 } }',
             'geometry IndexedFaceSet { solid TRUE creaseAngle 0.6',
             'coord Coordinate { point [']
    lines += [f'{x/2.54:.7f} {y/2.54:.7f} {z/2.54:.7f},' for x, y, z in vertices]
    lines += ['] } coordIndex [']
    lines += [','.join(map(str, face)) + ',-1,' for face in faces]
    return '\n'.join(lines + ['] } }'])


def main():
    parts = ['#VRML V2.0 utf8', '# Generated by mechanical/crystal_hc49s/generate_model.py',
             '# KiCad units: 0.1 inch. PCB top z=0. Body top z=3.5 mm.',
             prism(stadium(11.4, 4.8), 0, 0.35, (0.63, 0.65, 0.67)),
             prism(stadium(10.2, 3.8), 0.35, 3.5, (0.76, 0.78, 0.80))]
    for x in (0, 4.88):
        circle = [(x + 0.215 * math.cos(math.radians(a)),
                   0.215 * math.sin(math.radians(a))) for a in range(0, 360, 15)]
        parts.append(prism(circle, -3, 0.1, (0.72, 0.74, 0.76)))
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text('\n'.join(parts) + '\n')
    print(OUT)


if __name__ == '__main__':
    main()
